[package]
name = "soldout-login"
version = "0.1.0"
authors = ["Dio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
